import { NextRequest } from "next/server";
import { and, eq, desc, sql } from "drizzle-orm";
import { db, schema } from "@/lib/db";

export const runtime = "nodejs";

const VALID_PROVIDERS = ["anthropic", "openai", "gemini", "fallback"];

export async function GET(
  req: NextRequest,
  ctx: { params: Promise<{ slug: string }> },
) {
  const { slug } = await ctx.params;

  // Optional ?provider= serves that provider's newest file; the bare URL stays
  // the canonical llms.txt and keeps the default provider-priority pick.
  const provider = req.nextUrl.searchParams.get("provider");
  if (provider !== null && !VALID_PROVIDERS.includes(provider)) {
    return new Response(`# Bad request\n\nUnknown provider "${provider}". Valid: ${VALID_PROVIDERS.join(", ")}.\n`, {
      status: 400,
      headers: { "content-type": "text/plain; charset=utf-8" },
    });
  }

  const [site] = await db
    .select()
    .from(schema.sites)
    .where(eq(schema.sites.slug, slug))
    .limit(1);

  if (!site) {
    return new Response("# Not found\n\nNo llms.txt generated for this site.\n", {
      status: 404,
      headers: { "content-type": "text/plain; charset=utf-8" },
    });
  }

  // Serve the newest version. Within that version several providers may have
  // generated in parallel, so pick deterministically: prefer LLM-grounded output
  // over fallback, then a stable provider priority (Claude → GPT → Gemini).
  // With ?provider= the filter pins one provider and version desc picks its newest.
  const [generation] = await db
    .select()
    .from(schema.generations)
    .where(
      provider
        ? and(
            eq(schema.generations.siteId, site.id),
            eq(schema.generations.provider, provider),
          )
        : eq(schema.generations.siteId, site.id),
    )
    .orderBy(
      desc(schema.generations.version),
      sql`case when ${schema.generations.mode} = 'llm' then 0 else 1 end`,
      sql`case ${schema.generations.provider}
            when 'anthropic' then 0
            when 'openai' then 1
            when 'gemini' then 2
            else 3 end`,
    )
    .limit(1);

  if (!generation) {
    // A pinned provider that never generated for this site is a miss, not "pending".
    if (provider) {
      return new Response(`# Not available\n\nNo llms.txt has been generated by provider "${provider}" for this site.\n`, {
        status: 404,
        headers: { "content-type": "text/plain; charset=utf-8" },
      });
    }
    return new Response("# Pending\n\nllms.txt has not been generated yet.\n", {
      status: 202,
      headers: { "content-type": "text/plain; charset=utf-8" },
    });
  }

  return new Response(generation.content, {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "cache-control": "public, max-age=300, stale-while-revalidate=3600",
    },
  });
}
